import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import PWAInstallPrompt from "@/components/PWAInstallPrompt";
import PWAUpdateListener from "@/components/PWAUpdateListener";
import BrowserGate from "@/components/BrowserGate";

export const viewport: Viewport = {
  // The EXACT hex of --background (oklch(0.141 0.005 285.823)), so the Android
  // status bar in the installed PWA blends into the app instead of sitting
  // above it as an amber band. The app forces dark mode, so one value is
  // correct in every condition — there is no light theme to answer for.
  // Amber stays the accent colour; it was never meant to be system chrome.
  themeColor: '#09090b',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false, // Essential for POS to prevent UI shifting during fast scanning
  // Required for env(safe-area-inset-*) to report real values. Without it the
  // insets are all 0, and because appleWebApp.statusBarStyle below is
  // "black-translucent" (which extends the page under the iOS status bar and
  // home indicator), content rendered under the notch with nothing to
  // compensate for it.
  viewportFit: 'cover',
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Golden Squirrel - POS System",
  description: "Mobile Point of Sale for Golden Squirrel",
  manifest: "/manifest.json",
  icons: [
    {
      rel: "icon",
      url: "/icons/launchericon-192x192.png",
      sizes: "192x192",
      type: "image/png",
    },
    {
      rel: "icon",
      url: "/icons/launchericon-512x512.png",
      sizes: "512x512",
      type: "image/png",
    },
    {
      // iOS expects 180x180 for the home-screen icon. This was pointing at
      // the 192 launcher icon, which iOS downscales.
      rel: "apple-touch-icon",
      url: "/icons/apple-touch-icon-180x180.png",
      sizes: "180x180",
      type: "image/png",
    },

    // ---- iOS launch screens ----
    //
    // Without these an installed iOS PWA shows a BLANK WHITE SCREEN for its
    // entire cold boot — and iOS launches a cold WebView every single time, so
    // that blank screen is most of what "the app takes a long time to open"
    // means on an iPhone. They are a solid `#09090b` (the exact `themeColor`
    // above) with the launcher icon centred, so a launch reads as the app
    // starting rather than as a page loading.
    //
    // Generated by `node scripts/generate-splash.mjs`, whose header explains
    // the two traps: the size must match the device EXACTLY or iOS ignores it,
    // and they must NOT be precached — iOS shows the image before the web app
    // runs, so the service worker is not alive to serve it. `/splash/` is in
    // `workboxOptions.exclude` for that reason.
    //
    // Portrait only, deliberately: a device launched in landscape falls back to
    // today's behaviour rather than showing something wrong.
    {
      rel: "apple-touch-startup-image",
      url: "/splash/iphone-se-750x1334.png",
      media:
        "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
    },
    {
      rel: "apple-touch-startup-image",
      url: "/splash/iphone-8-plus-1242x2208.png",
      media:
        "(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
    },
    {
      rel: "apple-touch-startup-image",
      url: "/splash/iphone-x-1125x2436.png",
      media:
        "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
    },
    {
      rel: "apple-touch-startup-image",
      url: "/splash/iphone-xr-828x1792.png",
      media:
        "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
    },
    {
      rel: "apple-touch-startup-image",
      url: "/splash/iphone-xs-max-1242x2688.png",
      media:
        "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
    },
    {
      rel: "apple-touch-startup-image",
      url: "/splash/iphone-12-1170x2532.png",
      media:
        "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
    },
    {
      rel: "apple-touch-startup-image",
      url: "/splash/iphone-14-pro-1179x2556.png",
      media:
        "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
    },
    {
      rel: "apple-touch-startup-image",
      url: "/splash/iphone-16-pro-1206x2622.png",
      media:
        "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
    },
    {
      rel: "apple-touch-startup-image",
      url: "/splash/iphone-12-pro-max-1284x2778.png",
      media:
        "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
    },
    {
      rel: "apple-touch-startup-image",
      url: "/splash/iphone-14-pro-max-1290x2796.png",
      media:
        "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
    },
    {
      rel: "apple-touch-startup-image",
      url: "/splash/iphone-16-pro-max-1320x2868.png",
      media:
        "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
    },
    {
      rel: "apple-touch-startup-image",
      url: "/splash/ipad-1536x2048.png",
      media:
        "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
    },
    {
      rel: "apple-touch-startup-image",
      url: "/splash/ipad-air-1640x2360.png",
      media:
        "(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
    },
    {
      rel: "apple-touch-startup-image",
      url: "/splash/ipad-pro-11-1668x2388.png",
      media:
        "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
    },
    {
      rel: "apple-touch-startup-image",
      url: "/splash/ipad-pro-13-2048x2732.png",
      media:
        "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
    },
  ],
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Golden Squirrel",
  },
  formatDetection: {
    telephone: false,
  },
  // These "other" tags help with various Android and legacy browser PWA behaviors
  other: {
    'mobile-web-app-capable': 'yes',
    'msapplication-tap-highlight': 'no',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        {/* Must stay the first thing in the body: it decides whether this
            browser can render the app at all, before React hydrates. */}
        <BrowserGate />
        <Providers>
          {children}
          <PWAInstallPrompt />
          <PWAUpdateListener />
        </Providers>
      </body>
    </html>
  );
}